[package]
name = "sigmap"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
libc = "0.2.139"
nix = "0.26.2"
signal-hook = "0.3.14"
